# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Build
on:
  push:
    branches: [ TestGithub ]
  pull_request_target:
    types: [ opened, synchronize, reopened, edited ]
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f github/requirements.txt ]; then pip install -r github/requirements.txt; fi
    - name: Validate challenge
      run: |
        python3 github/challenge_processing_script.py
      env:
        IS_VALIDATION: "True"
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create or update challenge
      run: |
        python3 github/challenge_processing_script.py
      env:
        IS_VALIDATION: "False"
